"""Change file_url to JSON file_urls list

Revision ID: 8d288a663f92
Revises: dc11f7ff8206
Create Date: 2026-04-22 23:33:18.835770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d288a663f92'
down_revision: Union[str, Sequence[str], None] = 'dc11f7ff8206'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_urls', sa.JSON(), nullable=True))
    op.drop_column('chat_messages', 'file_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_url', sa.VARCHAR(), nullable=True))
    op.drop_column('chat_messages', 'file_urls')
    # ### end Alembic commands ###
