"""Add file URL to chat

Revision ID: dc11f7ff8206
Revises: c313b0d968a7
Create Date: 2026-04-22 23:27:14.087187

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc11f7ff8206'
down_revision: Union[str, Sequence[str], None] = 'c313b0d968a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_messages', sa.Column('file_url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_messages', 'file_url')
    # ### end Alembic commands ###
